// src/app/dashboard/ta/page.tsx
"use client";

import { DashboardLayout } from "@/components/dashboard/dashboard-layout";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { requireRole } from "@/lib/user-utils";
import { getTAAssignments, Assignment, Submission } from "@/lib/data-utils";
import { GradingModal } from "@/components/modals/grading-modal";
import { FileText, Clock, CheckCircle, Star, BarChart3 } from "lucide-react";
import { useState, useEffect } from "react";

interface TADashboardData {
  assignments: (Assignment & {
    submissions_count: number;
    graded_count: number;
    average_grade: number | null;
  })[];
  pendingGrading: (Submission & {
    assignment: Assignment;
    student: { first_name: string; last_name: string };
  })[];
  stats: {
    total: number;
    pending: number;
    graded_today: number;
    average_grade: number | null;
  };
}

export default function TADashboard() {
  const [userProfile, setUserProfile] = useState<any>(null);
  const [data, setData] = useState<TADashboardData | null>(null);
  const [loading, setLoading] = useState(true);
  const [gradingModalOpen, setGradingModalOpen] = useState(false);
  const [selectedSubmissionId, setSelectedSubmissionId] = useState<
    string | null
  >(null);

  useEffect(() => {
    loadData();
  }, []);

  const loadData = async () => {
    try {
      const profile = await requireRole("ta");
      setUserProfile(profile);

      const dashboardData = await getTAAssignments(profile);
      setData(dashboardData);
    } catch (error) {
      console.error("Failed to load dashboard data:", error);
    } finally {
      setLoading(false);
    }
  };

  const handleGradeClick = (submissionId: string) => {
    setSelectedSubmissionId(submissionId);
    setGradingModalOpen(true);
  };

  const handleGradeSubmitted = () => {
    // Reload data after grading
    loadData();
  };

  if (loading || !userProfile || !data) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <div className="text-center">
          <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600 mx-auto mb-4"></div>
          <p>Loading dashboard...</p>
        </div>
      </div>
    );
  }

  const formatGrade = (averageGrade: number | null) => {
    if (!averageGrade) return "N/A";

    let letterGrade = "F";
    if (averageGrade >= 90) letterGrade = "A";
    else if (averageGrade >= 80) letterGrade = "B";
    else if (averageGrade >= 70) letterGrade = "C";
    else if (averageGrade >= 60) letterGrade = "D";

    return letterGrade;
  };

  return (
    <>
      <DashboardLayout
        userProfile={userProfile}
        title="Teaching Assistant Dashboard"
        description="Grade assignments and manage submissions."
        requiredRole="ta"
      >
        <div className="grid gap-6">
          {/* Quick Stats */}
          <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
            <Card>
              <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                <CardTitle className="text-sm font-medium">
                  Total Assignments
                </CardTitle>
                <FileText className="h-4 w-4 text-muted-foreground" />
              </CardHeader>
              <CardContent>
                <div className="text-2xl font-bold">{data.stats.total}</div>
              </CardContent>
            </Card>

            <Card>
              <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                <CardTitle className="text-sm font-medium">
                  Pending Grading
                </CardTitle>
                <Clock className="h-4 w-4 text-muted-foreground" />
              </CardHeader>
              <CardContent>
                <div className="text-2xl font-bold">{data.stats.pending}</div>
              </CardContent>
            </Card>

            <Card>
              <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                <CardTitle className="text-sm font-medium">
                  Graded Today
                </CardTitle>
                <CheckCircle className="h-4 w-4 text-muted-foreground" />
              </CardHeader>
              <CardContent>
                <div className="text-2xl font-bold">
                  {data.stats.graded_today}
                </div>
              </CardContent>
            </Card>

            <Card>
              <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                <CardTitle className="text-sm font-medium">
                  Average Grade
                </CardTitle>
                <Star className="h-4 w-4 text-muted-foreground" />
              </CardHeader>
              <CardContent>
                <div className="text-2xl font-bold">
                  {data.stats.average_grade
                    ? formatGrade(data.stats.average_grade)
                    : "N/A"}
                </div>
              </CardContent>
            </Card>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            {/* Assignments Overview */}
            <Card>
              <CardHeader>
                <CardTitle>Assignment Overview</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="space-y-4">
                  {data.assignments.length === 0 ? (
                    <div className="text-center py-8 text-gray-500">
                      <FileText className="h-12 w-12 mx-auto mb-4 text-gray-300" />
                      <p>
                        No assignments found. You may not be assigned to any
                        courses yet.
                      </p>
                    </div>
                  ) : (
                    data.assignments.map((assignment) => (
                      <div
                        key={assignment.id}
                        className="flex items-center justify-between p-4 border rounded-lg"
                      >
                        <div>
                          <h3 className="font-medium text-gray-900">
                            {assignment.title}
                          </h3>
                          <p className="text-sm text-gray-500">
                            {assignment.course?.code || "Unknown Course"} • Due:{" "}
                            {new Date(assignment.due_date).toLocaleDateString()}
                          </p>
                          <div className="flex items-center space-x-4 mt-2 text-sm text-gray-600">
                            <span>
                              {assignment.submissions_count} submissions
                            </span>
                            <span>{assignment.graded_count} graded</span>
                            <span>
                              Avg: {formatGrade(assignment.average_grade)}
                            </span>
                          </div>
                        </div>
                      </div>
                    ))
                  )}
                </div>
              </CardContent>
            </Card>

            {/* Pending Grading Queue */}
            <Card>
              <CardHeader>
                <CardTitle>Pending Grading Queue</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="space-y-4">
                  {data.pendingGrading.length === 0 ? (
                    <div className="text-center py-8 text-gray-500">
                      <CheckCircle className="h-12 w-12 mx-auto mb-4 text-gray-300" />
                      <p>No pending submissions to grade. Great job!</p>
                    </div>
                  ) : (
                    data.pendingGrading.map((item) => (
                      <div
                        key={item.id}
                        className="flex items-center justify-between p-4 border rounded-lg hover:bg-gray-50"
                      >
                        <div>
                          <h3 className="font-medium text-gray-900">
                            {item.student?.first_name} {item.student?.last_name}
                          </h3>
                          <p className="text-sm text-gray-500">
                            {item.assignment?.title}
                          </p>
                          <p className="text-xs text-gray-400">
                            Submitted:{" "}
                            {item.submitted_at
                              ? new Date(item.submitted_at).toLocaleDateString()
                              : "Unknown"}
                          </p>
                        </div>

                        <div className="flex items-center space-x-2">
                          <Button
                            size="sm"
                            variant="outline"
                            onClick={() => handleGradeClick(item.id)}
                          >
                            Grade
                          </Button>
                        </div>
                      </div>
                    ))
                  )}
                </div>
              </CardContent>
            </Card>
          </div>
        </div>
      </DashboardLayout>

      <GradingModal
        isOpen={gradingModalOpen}
        onClose={() => {
          setGradingModalOpen(false);
          setSelectedSubmissionId(null);
        }}
        submissionId={selectedSubmissionId}
        onGradeSubmitted={handleGradeSubmitted}
      />
    </>
  );
}

// src/routes/dashboard/ta/+page.svelte
<script lang="ts">
	import Card from '$lib/components/ui/card.svelte';
import CardContent from '$lib/components/ui/card-content.svelte';
import CardHeader from '$lib/components/ui/card-header.svelte';
import CardTitle from '$lib/components/ui/card-title.svelte';
	import Button from '$lib/components/ui/button.svelte';
	import { FileText, Clock, CheckCircle, Users, TrendingUp } from 'lucide-svelte';
	import type { PageData } from './$types';

	export let data: PageData;

	function formatGrade(averageGrade: number | null) {
		if (!averageGrade) return 'N/A';

		let letterGrade = 'F';
		if (averageGrade >= 90) letterGrade = 'A';
		else if (averageGrade >= 80) letterGrade = 'B';
		else if (averageGrade >= 70) letterGrade = 'C';
		else if (averageGrade >= 60) letterGrade = 'D';

		return letterGrade;
	}
</script>

<svelte:head>
	<title>TA Dashboard - AI Grading Platform</title>
</svelte:head>

<div class="space-y-6">
	<!-- Quick Stats -->
	<div class="grid grid-cols-1 md:grid-cols-4 gap-4">
		<Card>
			<CardHeader class="flex flex-row items-center justify-between space-y-0 pb-2">
				<CardTitle class="text-sm font-medium">Total Assignments</CardTitle>
				<FileText class="h-4 w-4 text-muted-foreground" />
			</CardHeader>
			<CardContent>
				<div class="text-2xl font-bold">{data.stats.total}</div>
			</CardContent>
		</Card>

		<Card>
			<CardHeader class="flex flex-row items-center justify-between space-y-0 pb-2">
				<CardTitle class="text-sm font-medium">Pending Grading</CardTitle>
				<Clock class="h-4 w-4 text-muted-foreground" />
			</CardHeader>
			<CardContent>
				<div class="text-2xl font-bold">{data.stats.pending}</div>
			</CardContent>
		</Card>

		<Card>
			<CardHeader class="flex flex-row items-center justify-between space-y-0 pb-2">
				<CardTitle class="text-sm font-medium">Graded Today</CardTitle>
				<CheckCircle class="h-4 w-4 text-muted-foreground" />
			</CardHeader>
			<CardContent>
				<div class="text-2xl font-bold">{data.stats.graded_today}</div>
			</CardContent>
		</Card>

		<Card>
			<CardHeader class="flex flex-row items-center justify-between space-y-0 pb-2">
				<CardTitle class="text-sm font-medium">Average Grade</CardTitle>
				<TrendingUp class="h-4 w-4 text-muted-foreground" />
			</CardHeader>
			<CardContent>
				<div class="text-2xl font-bold">
					{data.stats.average_grade ? formatGrade(data.stats.average_grade) : 'N/A'}
				</div>
			</CardContent>
		</Card>
	</div>

	<div class="grid grid-cols-1 lg:grid-cols-2 gap-6">
		<!-- Assignments Overview -->
		<Card>
			<CardHeader>
				<CardTitle>Your Assignments</CardTitle>
			</CardHeader>
			<CardContent>
				<div class="space-y-4">
					{#if data.assignments.length === 0}
						<div class="text-center py-8 text-gray-500">
							<FileText class="h-12 w-12 mx-auto mb-4 text-gray-300" />
							<p>No assignments assigned to you yet.</p>
						</div>
					{:else}
						{#each data.assignments as assignment}
							<div class="flex items-center justify-between p-4 border rounded-lg">
								<div>
									<h3 class="font-medium text-gray-900">{assignment.title}</h3>
									<p class="text-sm text-gray-500">
										{assignment.course?.code || 'Unknown Course'} • Due: {new Date(assignment.due_date).toLocaleDateString()}
									</p>
									<div class="flex items-center space-x-4 mt-1 text-sm text-gray-600">
										<span>{assignment.submissions_count} submissions</span>
										<span>{assignment.graded_count} graded</span>
										{#if assignment.average_grade}
											<span>Avg: {formatGrade(assignment.average_grade)}</span>
										{/if}
									</div>
								</div>
								<Button size="sm" variant="outline">
									View
								</Button>
							</div>
						{/each}
					{/if}
				</div>
			</CardContent>
		</Card>

		<!-- Pending Grading -->
		<Card>
			<CardHeader>
				<CardTitle>Pending Grading</CardTitle>
			</CardHeader>
			<CardContent>
				<div class="space-y-4">
					{#if data.pendingGrading.length === 0}
						<div class="text-center py-8 text-gray-500">
							<CheckCircle class="h-12 w-12 mx-auto mb-4 text-gray-300" />
							<p>No pending submissions to grade.</p>
						</div>
					{:else}
						{#each data.pendingGrading as submission}
							<div class="flex items-center justify-between p-4 border rounded-lg hover:bg-gray-50">
								<div>
									<h3 class="font-medium text-gray-900">
										{submission.student.first_name} {submission.student.last_name}
									</h3>
									<p class="text-sm text-gray-500">
										{submission.assignment.title} • {submission.assignment.course?.code}
									</p>
									<p class="text-sm text-gray-600">
										Submitted: {new Date(submission.submitted_at!).toLocaleDateString()}
									</p>
								</div>
								<Button size="sm" variant="outline">
									Grade
								</Button>
							</div>
						{/each}
					{/if}
				</div>
			</CardContent>
		</Card>
	</div>
</div>
